# Generated by Django 3.2.19 on 2023-06-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvenTree', '0001_initial'),
    ]

    operations = [
    ]
